# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    ssh: https://github.com/xaque208/puppet-ssh.git
    sshkeys:
      repo: git://github.com/puppetlabs/puppetlabs-sshkeys_core.git
      puppet_version: '>= 6.0'
  forge_modules:
    stdlib: "puppetlabs/stdlib"
